### ISSUE TITLE
dont work -  não funciona

### ISSUE THREAD

**Issue by facuquilmes123** [Al0nnso/SorteioCom#1]
anexado pegar o erro

attached catch the error
![Captura](https://user-images.githubusercontent.com/63804749/84713300-0d5aa200-af41-11ea-87e6-7155360901e4.JPG)

**Comment by Al0nnso** [comment]
Olá arrumei o bug, o **.load() do jquery** que carrega os layouts HTML é bloqueado pelo **CORS** pelo url **file://**  , o **index.html** deve ser executado no firefox ou em um live server, mais informações no **README.md**

**Comment by Gpiza** [comment]
Uma pergunta ele so carrega 9mil comentario devidoo token da API?

**Comment by Al0nnso** [comment]
> Uma pergunta ele so carrega 9mil comentario devidoo token da API?

Ele só carrega 9mil pq é o limite do Instagram, se aumentar muito pode ser que ele retorne 429 Too Many Requests
Mas pode ser que ele carregue + só vai ter que colocar + delay para não ser bloqueado
